### ISSUE TITLE
Inverted plots

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/shadeMS#10]
Sometimes plots are upside down, because why not?

https://github.com/IanHeywood/shadeMS/blob/master/ShadeMS/shadeMS.py#L44

Changing the `origin` here from `'upper'` to `'lower'` fixes it, but I have no idea what decides which it needs to be to begin with.

**Comment by o-smirnov** [comment]
Never seen it in the new iteration, so let's close...
