### ISSUE TITLE
Empty plot not trapped, frame limits are bizarre

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/shadeMS#19]
Not sure what happened here (yet)...

![plot-1559762398_sdp_l0 full_1284 full_pol_wtspec-GLEAMJ140421-340018-XX-Imag_vs_Real](https://user-images.githubusercontent.com/6533799/79570683-d2a7cb00-80b1-11ea-9147-925f86592722.png)

**Comment by o-smirnov** [comment]
Well I guess we know that flagging still works!

This can probably be trapped by comparing datamin to datamax.
