### ISSUE TITLE
Baseline iterator leads to sparsification in BASELINE plots

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/shadeMS#41]
e.g.

![plot-1587194692_sdp_l0_wtspec-J0408-6545-scan_1-FREQ-BASELINE-CORRECTED_DATA-amp](https://user-images.githubusercontent.com/6533799/80288084-679f6980-872d-11ea-8d67-f83fc24dd302.png)

**Comment by o-smirnov** [comment]
I believe this is fixed.
