### ISSUE TITLE
pip install fails with llvmlite error

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/shadeMS#43]
As reported by Michael Janssen: https://pastebin.com/4bhsQT0b

I can reproduce. It looks like a broken version of ``llvmlite`` has been uploaded to PyPI. And a ["broken" version of python-casacore](https://github.com/kernsuite/packaging/issues/221) to boot, fun fun.

**Comment by o-smirnov** [comment]
Actually scratch that. I can only reproduce in a limited way:

* inside a new virtualenv, everything installs perfectly (unlike for Michael!)

* outside of a virtualenv, I **can** pip3 install llvmlite, I **can't** pip install llvmlite, and I **can't** pip or pip3 install python-casacore due to the issue linked above.

No idea what's going on really due to my lack of experience with pip, maybe @Athanaseus or @gijzelaerr can suggest something?

Michael, in the meantime, let's try some workarounds. Please try ``pip3 install llvmlite`` by itself in your virtualenv. Then ``pip3 install python-casacore``. And if that fails, ``pip3 install python-casacore==3.2.0``. If those succeed, try installing shadems again.

**Comment by mjanssen2308** [comment]
The issues seems to be with llvmlite, casacore installs fine.
I have not much experience with virtualenv. Maybe I need to have python 3.8 there?

michael@mjpc:~/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest$ virtualenv -p python3 .
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3
Also creating executable in /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
michael@mjpc:~/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest$ source bin/activate
(shadeMStest) michael@mjpc:~/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest$ pip3 install llvmlite
Collecting llvmlite
  Using cached llvmlite-0.32.0.tar.gz (103 kB)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ymw8dcpy/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ymw8dcpy/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ai_mt5wa
       cwd: /tmp/pip-install-ymw8dcpy/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3 /tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 106, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.5/subprocess.py", line 693, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
      raise child_exception_type(errno_num, err_msg)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 168, in <module>
      main()
    File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 158, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 109, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ymw8dcpy/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ymw8dcpy/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bzpo2dq5/install-record.txt --single-version-externally-managed --compile --install-headers /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/include/site/python3.5/llvmlite
         cwd: /tmp/pip-install-ymw8dcpy/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-ymw8dcpy/llvmlite/llvmlite/_version.py {'full': '26059d238f4ba23dff74703dd27168591d889edd', 'version': '0.32.0'}
    running build_ext
    /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3 /tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 106, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 693, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 168, in <module>
        main()
      File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 158, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-ymw8dcpy/llvmlite/ffi/build.py", line 109, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ymw8dcpy/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ymw8dcpy/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bzpo2dq5/install-record.txt --single-version-externally-managed --compile --install-headers /home/michael/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest/include/site/python3.5/llvmlite Check the logs for full command output.
(shadeMStest) michael@mjpc:~/data_collections/CASA/VLBA_M87_03-Jun/shadeMStest$ pip3 install python-casacore
Collecting python-casacore
  Using cached python_casacore-3.3.0-cp35-cp35m-manylinux2010_x86_64.whl (25.6 MB)
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting numpy
  Using cached numpy-1.18.3-cp35-cp35m-manylinux1_x86_64.whl (20.0 MB)
Processing /home/michael/.cache/pip/wheels/c4/f0/ae/d4689c4532d1f111462ed6a884a7767d502e511ee65f0d8e1b/future-0.18.2-py3-none-any.whl
Installing collected packages: six, argparse, numpy, future, python-casacore
Successfully installed argparse-1.4.0 future-0.18.2 numpy-1.18.3 python-casacore-3.3.0 six-1.14.0

**Comment by o-smirnov** [comment]
No, I'm running it with python3.6, that's fine. I suspect your system needs LLVM packages to be installed (these are binary packages outside the PyPI infrastructure, so pip can't pull them in). What does 

```
$ dpkg -la | grep llvm
```

say? If this is Ubuntu, try apt installing ``libllvm9`` or something like that.

**Comment by sjperkins** [comment]
I suspect this is related to numba which installs llvmlite. I don't think it needs an LLVM system install.

**Comment by mjanssen2308** [comment]
dpkg -la | grep llvm
ii  libllvm3.8:amd64                                            1:3.8-2ubuntu4                                amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm6.0:amd64                                            1:6.0-1ubuntu2~16.04.1                        amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm6.0:i386                                             1:6.0-1ubuntu2~16.04.1                        i386         Modular compiler and toolchain technologies, runtime library

**Comment by o-smirnov** [comment]
@mjanssen2308, could you try installing the ``llvm-6.0`` package then?

**Comment by sjperkins** [comment]
https://github.com/numba/llvmlite#compatibility  

> llvmlite works with Python 3.6 and greater.
> As of version 0.29.0, llvmlite requires LLVM 7.0.x or later
> Historical compatibility table:

**Comment by o-smirnov** [comment]
OK I just installed ``llvmlite`` on another box, which has only these installed:
```
oms@com08:~$ dpkg -la | grep llvm
ii  libllvm6.0:amd64                          1:6.0-1ubuntu2                                  amd64        Modular compiler and toolchain technologies, runtime library
ii  libllvm9:amd64                            1:9-2~ubuntu18.04.2                             amd64        Modular compiler and toolchain technologies, runtime library
```

**Comment by o-smirnov** [comment]
I suspect ``libllvm9`` might be the one minimal requirement. I can't uninstall it without wiping out a whole slew of other useful packages. @mjanssen2308 forget my previous suggestion -- please rather try installing ``libllvm9``.

**Comment by mjanssen2308** [comment]
I am still running Ubuntu 16.04 and it seems like libllvm9 is not readily available.
I installed libllvm8 instead but the problem persists.

**Comment by o-smirnov** [comment]
OK, I have the same failure on a 16.04 box. Well hey, when LTS+1+1 is coming out, you know it just *might*, just *might* be time to start thinking about an upgrade... :P

**Comment by o-smirnov** [comment]
OK, libllvm8 is insufficient, but this worked for me on 16.04:

```
sudo apt install llvm-8
export LLVM_CONFIG=/usr/bin/llvm-config-8
pip install llvmlite
```

**Comment by mjanssen2308** [comment]
Yep, this works, thanks.
Point well taken regarding Ubuntu... I become sloppy when a laptop is about to be retired ;)

**Comment by o-smirnov** [comment]
I think this is resolved, but feel free to reopen.
