### ISSUE TITLE
uv plot coloured by baseline

### ISSUE THREAD

**Issue by tremou** [ratt-ru/shadeMS#48]
Hi, 
thanks very much for this useful tool! 

I get some weird points to the right side of the plot when, I  plot  `shadems --xaxis U --yaxis V --colour-by BASELINE myms`
While the default:  `shadems --xaxis U --yaxis V myms` seems reasonable. 
Any thoughts? 
Thanks, 
Lilia

![plot-gx339-4_april25_2020-V-U-BASELINE](https://user-images.githubusercontent.com/11620820/80620698-9b88d080-8a46-11ea-92d0-1e3461b76a3c.png)
![plot-gx339-4_april25_2020-V-U](https://user-images.githubusercontent.com/11620820/80620721-a479a200-8a46-11ea-9393-3bec686d24b1.png)

**Comment by IanHeywood** [comment]
Looks like the conjugate points are missing too.

**Comment by IanHeywood** [comment]
Actually looks like each colour might have its own offset origin or something. Fairly sure those cyan and magenta points at u ~ 10,000 at the top of the figure shouldn't be converging like that.

**Comment by tremou** [comment]
Ooops sorry. There you go. I had a second run by defining -noconj (which is the one I shared above) and here it is with conj points 

![plot-gx339-4_april25_2020-V-U-BASELINE_conj](https://user-images.githubusercontent.com/11620820/80621992-69786e00-8a48-11ea-947e-34213f765184.png)

**Comment by o-smirnov** [comment]
Wow. Inconceivable! I'll see what I can turn up tomorrow...

**Comment by o-smirnov** [comment]
PS. @tremou, this is with the master branch? Could you please also try with the ``auto-bounds`` branch?

**Comment by tremou** [comment]
Yes that is with the master branch. Sure, I will give the auto-bounds branch a try, too .

Thanks!

**Comment by o-smirnov** [comment]
Please let me know. And double-check that you've got my version of datashader installed...

**Comment by tremou** [comment]
With `auto-bounds` branch, I do not get this weird right points. Yes I double checked, in both cases I use the datashader from your repo: 

![plot-gx339-4_april25_2020-V-U-BASELINE](https://user-images.githubusercontent.com/11620820/80695988-0a156f00-8ad7-11ea-977a-8dd6a15cec20.png)
![plot-gx339-4_april25_2020-V-U](https://user-images.githubusercontent.com/11620820/80696058-1f8a9900-8ad7-11ea-9ede-ced214b30229.png)

**Comment by o-smirnov** [comment]
OK I'm disinclined to hunt bugs in master then, since I fixed many things on my branch.

Is blue/red the default colormap you get with ``-c BASELINE`` now? If so, that's a bug -- it should still be using the harlequin colormap that your original plots showed.

**Comment by tremou** [comment]
In neither cases I set the color so yes it should be the default. Thanks !

**Comment by o-smirnov** [comment]
@tremou try with the latest ``auto-bounds`` -- should be back to a more sensible colouring.

**Comment by o-smirnov** [comment]
Yep. You know it's working properly when you start craving psychedelics just by looking at it!
