### ISSUE TITLE
Getting error with fontsize

### ISSUE THREAD

**Issue by viralp** [ratt-ru/shadeMS#65]
Hi. I am getting the following error message while using the `--fontsize` option. Also could someone please explain to me about what is the difference in the colour (red and blue) of the attached U vs V image? 

Traceback (most recent call last):
  File "/home/parekh/venvclean/bin/shadems", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/parekh/shadeMS/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/home/parekh/shadeMS/shade_ms/main.py", line 739, in main
    render_single_plot(df, subset, xdatum, ydatum, adatum, ared, cdatum, pngname, title, xlabel, ylabel)
  File "/home/parekh/shadeMS/shade_ms/main.py", line 688, in render_single_plot
    options=options)
  File "/home/parekh/shadeMS/shade_ms/data_plots.py", line 503, in create_plot
    ax.tick_params(labelsize=options.fontsize*0.66)
TypeError: can't multiply sequence by non-int of type 'float'

![plot-field1_fixvis-Abell3376West_corr-V-U](https://user-images.githubusercontent.com/4331123/86245197-6bc28a00-bba9-11ea-9142-074b888f8cdb.png)

**Comment by IanHeywood** [comment]
The default colour scheme represents the density of points using the `coolwarm` palette. Red = high density of points, blue = low density of points, black = somewhere in between. Histogram equalisation will also be applied by default in this scenario.

**Comment by o-smirnov** [comment]
So what did you give for ``--fontsize``, @viralp? Could you please paste the full command?

**Comment by viralp** [comment]
I used  shadems --xaxis U --yaxis V --title " " --fontsize 30

**Comment by o-smirnov** [comment]
Haha, embarrassingly enough, it seems this option was never tested.

I have pushed a fix to the b050 branch.
