### ISSUE TITLE
--ant-num 1: results in IndexError

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/shadeMS#70]
``--ant-num 1:30`` works.

**Comment by rubyvanrooyen** [comment]
I think I accidentally fixed this bug in my feature branch (PR https://github.com/rubyvanrooyen/shadeMS/pull/17)

For a small array with 4 antennas:    
`4/4 antennas: 0:m010 1:m043 2:m053 3:m054`

I get the expected responses for all my permutations:    

- `shadems msfiles/small.ms --xaxis CHAN --yaxis DATA:phase --ant-num 1:`
gives
`2020-08-05 19:00:28 - shadems - INFO - Antenna name(s)  : m043 m053 m054`

and

- `shadems msfiles/small.ms --xaxis CHAN --yaxis DATA:phase --ant-num 1:4`
gives
`2020-08-05 19:01:47 - shadems - INFO - Antenna name(s)  : m043 m053 m054`

also

- `shadems msfiles/small.ms --xaxis CHAN --yaxis DATA:phase --ant-num 2:`
gives
`2020-08-05 19:10:02 - shadems - INFO - Antenna name(s)  : m053 m054`
