### ISSUE TITLE
Antenna - antenna plots

### ISSUE THREAD

**Issue by JonahDW** [ratt-ru/shadeMS#76]
More of a feature question? 

Plotting a grid with all the baseline amplitudes of DATA/MODEL for example is an excellent diagnostic tool, and I did hack this feature in a previous version of shadeMS, but the format is so different from the regular plots that it might a bit too specialized for the software. However, the querying in the module is well suited for it.

Is there a consideration towards implementing this, or might there be a different software module that already does something like this?

**Comment by o-smirnov** [comment]
Remind me what eactly you want to plot @JonahDW?  We do have support for stuff like this:

| | |
|-|-|
|![image](https://user-images.githubusercontent.com/6470079/89516927-54467480-d7d9-11ea-89da-f4573c5c0b15.png)|![image](https://user-images.githubusercontent.com/6470079/89516934-57416500-d7d9-11ea-8c9d-8531ec1d1785.png)|

**Comment by JonahDW** [comment]
Yes, this is what I am looking for! I didn't realize this was there, can I achieve this with the current version? If so, what would be the call?

**Comment by o-smirnov** [comment]
Something like
```
-x ANTENNA1 -y ANTENNA2 --aaxis CORRECTED_DATA:phase --ared std
```
...and ``std`` can also be e.g ``mean``, ``max``, etc. 

Note that I do want to merge the ``aaxis`` and ``caxis`` functionality in a future release (see #69), as there's quite a bit of conceptual overlap right now, which makes it a bit confusing.

**Comment by JonahDW** [comment]
Okay, good to know, this is really nice!
