### ISSUE TITLE
add --xhline and --yhline options and arbitrary --markup

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/shadeMS#79]
Some plots could benefit with lines at e.g. 0 to guide the eye.

**Comment by o-smirnov** [comment]
Had an even better idea -- it's pretty simple to make a generic thingy for invoking arbitrary matplotlib Axes methods. Just supply the arguments as a YaML string. For example, to call ``Axes.annotate()``:

```
shadems msdir/MS-pre_cal.ms -x real -y imag -c CORR --corr IQUV --dir plots --col CORRECTED_DATA --field J0521+1638 --vline 0: --hline 0: -M annotate "['This line is for Paolo', {xy: [0.2, 0], xytext: [0.4, -0.1], arrowprops: {facecolor: black, shrink: 0.05}}]"
```

![image](https://user-images.githubusercontent.com/6470079/95778845-37db2280-0cc9-11eb-85f7-13889b22830c.png)

**Comment by IanHeywood** [comment]
That's brilliant.
